"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import instamadilloCoreTypeMedia.InstamadilloCoreTypeMedia_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Collection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MEDIA_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def media(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[instamadilloCoreTypeMedia.InstamadilloCoreTypeMedia_pb2.Media]: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        media: collections.abc.Iterable[instamadilloCoreTypeMedia.InstamadilloCoreTypeMedia_pb2.Media] | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["name", b"name"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["media", b"media", "name", b"name"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Collection: typing_extensions.TypeAlias = Collection
