"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Reportable(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MINVERSION_FIELD_NUMBER: builtins.int
    MAXVERSION_FIELD_NUMBER: builtins.int
    NOTREPORTABLEMINVERSION_FIELD_NUMBER: builtins.int
    NEVER_FIELD_NUMBER: builtins.int
    minVersion: builtins.int
    maxVersion: builtins.int
    notReportableMinVersion: builtins.int
    never: builtins.bool
    def __init__(
        self,
        *,
        minVersion: builtins.int = ...,
        maxVersion: builtins.int = ...,
        notReportableMinVersion: builtins.int = ...,
        never: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["maxVersion", b"maxVersion", "minVersion", b"minVersion", "never", b"never", "notReportableMinVersion", b"notReportableMinVersion"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Reportable: typing_extensions.TypeAlias = Reportable

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> Global___Field: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: Global___Field | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["value", b"value"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    FIELD_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.int
    @property
    def field(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, Global___Field]: ...
    def __init__(
        self,
        *,
        field: collections.abc.Mapping[builtins.int, Global___Field] | None = ...,
        version: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["field", b"field", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Config: typing_extensions.TypeAlias = Config

@typing.final
class Field(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SubfieldEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> Global___Field: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: Global___Field | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["value", b"value"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    MINVERSION_FIELD_NUMBER: builtins.int
    MAXVERSION_FIELD_NUMBER: builtins.int
    NOTREPORTABLEMINVERSION_FIELD_NUMBER: builtins.int
    ISMESSAGE_FIELD_NUMBER: builtins.int
    SUBFIELD_FIELD_NUMBER: builtins.int
    minVersion: builtins.int
    maxVersion: builtins.int
    notReportableMinVersion: builtins.int
    isMessage: builtins.bool
    @property
    def subfield(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, Global___Field]: ...
    def __init__(
        self,
        *,
        minVersion: builtins.int = ...,
        maxVersion: builtins.int = ...,
        notReportableMinVersion: builtins.int = ...,
        isMessage: builtins.bool = ...,
        subfield: collections.abc.Mapping[builtins.int, Global___Field] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["isMessage", b"isMessage", "maxVersion", b"maxVersion", "minVersion", b"minVersion", "notReportableMinVersion", b"notReportableMinVersion", "subfield", b"subfield"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Field: typing_extensions.TypeAlias = Field
