"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeleteMessagePayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGEOTID_FIELD_NUMBER: builtins.int
    messageOtid: builtins.str
    def __init__(
        self,
        *,
        messageOtid: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageOtid", b"messageOtid"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageOtid", b"messageOtid"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteMessagePayload: typing_extensions.TypeAlias = DeleteMessagePayload
