"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
import waArmadilloXMA.WAArmadilloXMA_pb2
import waCommon.WACommon_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Armadillo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Metadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class Payload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONTENT_FIELD_NUMBER: builtins.int
        APPLICATIONDATA_FIELD_NUMBER: builtins.int
        SIGNAL_FIELD_NUMBER: builtins.int
        SUBPROTOCOL_FIELD_NUMBER: builtins.int
        @property
        def content(self) -> Global___Armadillo.Content: ...
        @property
        def applicationData(self) -> Global___Armadillo.ApplicationData: ...
        @property
        def signal(self) -> Global___Armadillo.Signal: ...
        @property
        def subProtocol(self) -> Global___Armadillo.SubProtocolPayload: ...
        def __init__(
            self,
            *,
            content: Global___Armadillo.Content | None = ...,
            applicationData: Global___Armadillo.ApplicationData | None = ...,
            signal: Global___Armadillo.Signal | None = ...,
            subProtocol: Global___Armadillo.SubProtocolPayload | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["applicationData", b"applicationData", "content", b"content", "payload", b"payload", "signal", b"signal", "subProtocol", b"subProtocol"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["applicationData", b"applicationData", "content", b"content", "payload", b"payload", "signal", b"signal", "subProtocol", b"subProtocol"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_payload: typing_extensions.TypeAlias = typing.Literal["content", "applicationData", "signal", "subProtocol"]
        _WhichOneofArgType_payload: typing_extensions.TypeAlias = typing.Literal["payload", b"payload"]
        def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

    @typing.final
    class SubProtocolPayload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FUTUREPROOF_FIELD_NUMBER: builtins.int
        futureProof: waCommon.WACommon_pb2.FutureProofBehavior.ValueType
        def __init__(
            self,
            *,
            futureProof: waCommon.WACommon_pb2.FutureProofBehavior.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["futureProof", b"futureProof"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["futureProof", b"futureProof"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class Signal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class EncryptedBackupsSecrets(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing.final
            class Epoch(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                class _EpochStatus:
                    ValueType = typing.NewType("ValueType", builtins.int)
                    V: typing_extensions.TypeAlias = ValueType

                class _EpochStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Signal.EncryptedBackupsSecrets.Epoch._EpochStatus.ValueType], builtins.type):
                    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                    ES_OPEN: Armadillo.Signal.EncryptedBackupsSecrets.Epoch._EpochStatus.ValueType  # 1
                    ES_CLOSE: Armadillo.Signal.EncryptedBackupsSecrets.Epoch._EpochStatus.ValueType  # 2

                class EpochStatus(_EpochStatus, metaclass=_EpochStatusEnumTypeWrapper): ...
                ES_OPEN: Armadillo.Signal.EncryptedBackupsSecrets.Epoch.EpochStatus.ValueType  # 1
                ES_CLOSE: Armadillo.Signal.EncryptedBackupsSecrets.Epoch.EpochStatus.ValueType  # 2

                ID_FIELD_NUMBER: builtins.int
                ANONID_FIELD_NUMBER: builtins.int
                ROOTKEY_FIELD_NUMBER: builtins.int
                STATUS_FIELD_NUMBER: builtins.int
                ID: builtins.int
                anonID: builtins.bytes
                rootKey: builtins.bytes
                status: Global___Armadillo.Signal.EncryptedBackupsSecrets.Epoch.EpochStatus.ValueType
                def __init__(
                    self,
                    *,
                    ID: builtins.int | None = ...,
                    anonID: builtins.bytes | None = ...,
                    rootKey: builtins.bytes | None = ...,
                    status: Global___Armadillo.Signal.EncryptedBackupsSecrets.Epoch.EpochStatus.ValueType | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["ID", b"ID", "anonID", b"anonID", "rootKey", b"rootKey", "status", b"status"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ID", b"ID", "anonID", b"anonID", "rootKey", b"rootKey", "status", b"status"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            BACKUPID_FIELD_NUMBER: builtins.int
            SERVERDATAID_FIELD_NUMBER: builtins.int
            EPOCH_FIELD_NUMBER: builtins.int
            TEMPOCMFCLIENTSTATE_FIELD_NUMBER: builtins.int
            MAILBOXROOTKEY_FIELD_NUMBER: builtins.int
            OBLIVIOUSVALIDATIONTOKEN_FIELD_NUMBER: builtins.int
            backupID: builtins.int
            serverDataID: builtins.int
            tempOcmfClientState: builtins.bytes
            mailboxRootKey: builtins.bytes
            obliviousValidationToken: builtins.bytes
            @property
            def epoch(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Armadillo.Signal.EncryptedBackupsSecrets.Epoch]: ...
            def __init__(
                self,
                *,
                backupID: builtins.int | None = ...,
                serverDataID: builtins.int | None = ...,
                epoch: collections.abc.Iterable[Global___Armadillo.Signal.EncryptedBackupsSecrets.Epoch] | None = ...,
                tempOcmfClientState: builtins.bytes | None = ...,
                mailboxRootKey: builtins.bytes | None = ...,
                obliviousValidationToken: builtins.bytes | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["backupID", b"backupID", "mailboxRootKey", b"mailboxRootKey", "obliviousValidationToken", b"obliviousValidationToken", "serverDataID", b"serverDataID", "tempOcmfClientState", b"tempOcmfClientState"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["backupID", b"backupID", "epoch", b"epoch", "mailboxRootKey", b"mailboxRootKey", "obliviousValidationToken", b"obliviousValidationToken", "serverDataID", b"serverDataID", "tempOcmfClientState", b"tempOcmfClientState"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        ENCRYPTEDBACKUPSSECRETS_FIELD_NUMBER: builtins.int
        @property
        def encryptedBackupsSecrets(self) -> Global___Armadillo.Signal.EncryptedBackupsSecrets: ...
        def __init__(
            self,
            *,
            encryptedBackupsSecrets: Global___Armadillo.Signal.EncryptedBackupsSecrets | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["encryptedBackupsSecrets", b"encryptedBackupsSecrets", "signal", b"signal"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["encryptedBackupsSecrets", b"encryptedBackupsSecrets", "signal", b"signal"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_signal: typing_extensions.TypeAlias = typing.Literal["encryptedBackupsSecrets"]
        _WhichOneofArgType_signal: typing_extensions.TypeAlias = typing.Literal["signal", b"signal"]
        def WhichOneof(self, oneof_group: _WhichOneofArgType_signal) -> _WhichOneofReturnType_signal | None: ...

    @typing.final
    class ApplicationData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class MessageHistoryDocumentMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            DOCUMENT_FIELD_NUMBER: builtins.int
            @property
            def document(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            def __init__(
                self,
                *,
                document: waCommon.WACommon_pb2.SubProtocol | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["document", b"document"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["document", b"document"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class AIBotResponseMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            SUMMONTOKEN_FIELD_NUMBER: builtins.int
            MESSAGETEXT_FIELD_NUMBER: builtins.int
            SERIALIZEDEXTRAS_FIELD_NUMBER: builtins.int
            summonToken: builtins.str
            messageText: builtins.str
            serializedExtras: builtins.str
            def __init__(
                self,
                *,
                summonToken: builtins.str | None = ...,
                messageText: builtins.str | None = ...,
                serializedExtras: builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageText", b"messageText", "serializedExtras", b"serializedExtras", "summonToken", b"summonToken"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageText", b"messageText", "serializedExtras", b"serializedExtras", "summonToken", b"summonToken"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class MetadataSyncAction(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing.final
            class SyncAttachmentInterventionAction(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                class _InterventionType:
                    ValueType = typing.NewType("ValueType", builtins.int)
                    V: typing_extensions.TypeAlias = ValueType

                class _InterventionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction._InterventionType.ValueType], builtins.type):
                    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                    UNKNOWN: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction._InterventionType.ValueType  # 0
                    NUDE: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction._InterventionType.ValueType  # 1
                    NOT_NUDE: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction._InterventionType.ValueType  # 2

                class InterventionType(_InterventionType, metaclass=_InterventionTypeEnumTypeWrapper): ...
                UNKNOWN: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction.InterventionType.ValueType  # 0
                NUDE: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction.InterventionType.ValueType  # 1
                NOT_NUDE: Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction.InterventionType.ValueType  # 2

                MESSAGEKEY_FIELD_NUMBER: builtins.int
                INTERVENTIONTYPE_FIELD_NUMBER: builtins.int
                interventionType: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction.InterventionType.ValueType
                @property
                def messageKey(self) -> waCommon.WACommon_pb2.MessageKey: ...
                def __init__(
                    self,
                    *,
                    messageKey: waCommon.WACommon_pb2.MessageKey | None = ...,
                    interventionType: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction.InterventionType.ValueType | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["interventionType", b"interventionType", "messageKey", b"messageKey"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["interventionType", b"interventionType", "messageKey", b"messageKey"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @typing.final
            class SyncSpectraAction(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                class _SpectraActionType:
                    ValueType = typing.NewType("ValueType", builtins.int)
                    V: typing_extensions.TypeAlias = ValueType

                class _SpectraActionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction._SpectraActionType.ValueType], builtins.type):
                    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                    TAKEDOWN: Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction._SpectraActionType.ValueType  # 0
                    RESTORE: Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction._SpectraActionType.ValueType  # 1

                class SpectraActionType(_SpectraActionType, metaclass=_SpectraActionTypeEnumTypeWrapper): ...
                TAKEDOWN: Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction.SpectraActionType.ValueType  # 0
                RESTORE: Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction.SpectraActionType.ValueType  # 1

                KEY_FIELD_NUMBER: builtins.int
                ACTIONTYPE_FIELD_NUMBER: builtins.int
                TAKEDOWNACTIONID_FIELD_NUMBER: builtins.int
                CONFIG_FIELD_NUMBER: builtins.int
                actionType: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction.SpectraActionType.ValueType
                takedownActionID: builtins.int
                config: builtins.str
                @property
                def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
                def __init__(
                    self,
                    *,
                    key: waCommon.WACommon_pb2.MessageKey | None = ...,
                    actionType: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction.SpectraActionType.ValueType | None = ...,
                    takedownActionID: builtins.int | None = ...,
                    config: builtins.str | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionType", b"actionType", "config", b"config", "key", b"key", "takedownActionID", b"takedownActionID"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionType", b"actionType", "config", b"config", "key", b"key", "takedownActionID", b"takedownActionID"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @typing.final
            class SyncMessageAction(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                @typing.final
                class ActionMessageDelete(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor

                    def __init__(
                        self,
                    ) -> None: ...

                MESSAGEDELETE_FIELD_NUMBER: builtins.int
                KEY_FIELD_NUMBER: builtins.int
                @property
                def messageDelete(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncMessageAction.ActionMessageDelete: ...
                @property
                def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
                def __init__(
                    self,
                    *,
                    messageDelete: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncMessageAction.ActionMessageDelete | None = ...,
                    key: waCommon.WACommon_pb2.MessageKey | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["action", b"action", "key", b"key", "messageDelete", b"messageDelete"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["action", b"action", "key", b"key", "messageDelete", b"messageDelete"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
                _WhichOneofReturnType_action: typing_extensions.TypeAlias = typing.Literal["messageDelete"]
                _WhichOneofArgType_action: typing_extensions.TypeAlias = typing.Literal["action", b"action"]
                def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

            @typing.final
            class SyncChatAction(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                @typing.final
                class ActionChatRead(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor

                    MESSAGERANGE_FIELD_NUMBER: builtins.int
                    READ_FIELD_NUMBER: builtins.int
                    read: builtins.bool
                    @property
                    def messageRange(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange: ...
                    def __init__(
                        self,
                        *,
                        messageRange: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange | None = ...,
                        read: builtins.bool | None = ...,
                    ) -> None: ...
                    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageRange", b"messageRange", "read", b"read"]
                    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageRange", b"messageRange", "read", b"read"]
                    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

                @typing.final
                class ActionChatDelete(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor

                    MESSAGERANGE_FIELD_NUMBER: builtins.int
                    @property
                    def messageRange(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange: ...
                    def __init__(
                        self,
                        *,
                        messageRange: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange | None = ...,
                    ) -> None: ...
                    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageRange", b"messageRange"]
                    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageRange", b"messageRange"]
                    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

                @typing.final
                class ActionChatArchive(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor

                    MESSAGERANGE_FIELD_NUMBER: builtins.int
                    ARCHIVED_FIELD_NUMBER: builtins.int
                    archived: builtins.bool
                    @property
                    def messageRange(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange: ...
                    def __init__(
                        self,
                        *,
                        messageRange: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessageRange | None = ...,
                        archived: builtins.bool | None = ...,
                    ) -> None: ...
                    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["archived", b"archived", "messageRange", b"messageRange"]
                    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["archived", b"archived", "messageRange", b"messageRange"]
                    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

                CHATARCHIVE_FIELD_NUMBER: builtins.int
                CHATDELETE_FIELD_NUMBER: builtins.int
                CHATREAD_FIELD_NUMBER: builtins.int
                CHATID_FIELD_NUMBER: builtins.int
                chatID: builtins.str
                @property
                def chatArchive(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatArchive: ...
                @property
                def chatDelete(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatDelete: ...
                @property
                def chatRead(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatRead: ...
                def __init__(
                    self,
                    *,
                    chatArchive: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatArchive | None = ...,
                    chatDelete: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatDelete | None = ...,
                    chatRead: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction.ActionChatRead | None = ...,
                    chatID: builtins.str | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["action", b"action", "chatArchive", b"chatArchive", "chatDelete", b"chatDelete", "chatID", b"chatID", "chatRead", b"chatRead"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["action", b"action", "chatArchive", b"chatArchive", "chatDelete", b"chatDelete", "chatID", b"chatID", "chatRead", b"chatRead"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
                _WhichOneofReturnType_action: typing_extensions.TypeAlias = typing.Literal["chatArchive", "chatDelete", "chatRead"]
                _WhichOneofArgType_action: typing_extensions.TypeAlias = typing.Literal["action", b"action"]
                def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

            @typing.final
            class SyncActionMessage(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                KEY_FIELD_NUMBER: builtins.int
                TIMESTAMP_FIELD_NUMBER: builtins.int
                timestamp: builtins.int
                @property
                def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
                def __init__(
                    self,
                    *,
                    key: waCommon.WACommon_pb2.MessageKey | None = ...,
                    timestamp: builtins.int | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "timestamp", b"timestamp"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "timestamp", b"timestamp"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @typing.final
            class SyncActionMessageRange(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                LASTMESSAGETIMESTAMP_FIELD_NUMBER: builtins.int
                LASTSYSTEMMESSAGETIMESTAMP_FIELD_NUMBER: builtins.int
                MESSAGES_FIELD_NUMBER: builtins.int
                lastMessageTimestamp: builtins.int
                lastSystemMessageTimestamp: builtins.int
                @property
                def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessage]: ...
                def __init__(
                    self,
                    *,
                    lastMessageTimestamp: builtins.int | None = ...,
                    lastSystemMessageTimestamp: builtins.int | None = ...,
                    messages: collections.abc.Iterable[Global___Armadillo.ApplicationData.MetadataSyncAction.SyncActionMessage] | None = ...,
                ) -> None: ...
                _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["lastMessageTimestamp", b"lastMessageTimestamp", "lastSystemMessageTimestamp", b"lastSystemMessageTimestamp"]
                def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
                _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["lastMessageTimestamp", b"lastMessageTimestamp", "lastSystemMessageTimestamp", b"lastSystemMessageTimestamp", "messages", b"messages"]
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            CHATACTION_FIELD_NUMBER: builtins.int
            MESSAGEACTION_FIELD_NUMBER: builtins.int
            SPECTRAACTION_FIELD_NUMBER: builtins.int
            ATTACHMENTINTERVENTIONACTION_FIELD_NUMBER: builtins.int
            ACTIONTIMESTAMP_FIELD_NUMBER: builtins.int
            actionTimestamp: builtins.int
            @property
            def chatAction(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction: ...
            @property
            def messageAction(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncMessageAction: ...
            @property
            def spectraAction(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction: ...
            @property
            def attachmentInterventionAction(self) -> Global___Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction: ...
            def __init__(
                self,
                *,
                chatAction: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncChatAction | None = ...,
                messageAction: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncMessageAction | None = ...,
                spectraAction: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncSpectraAction | None = ...,
                attachmentInterventionAction: Global___Armadillo.ApplicationData.MetadataSyncAction.SyncAttachmentInterventionAction | None = ...,
                actionTimestamp: builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionTimestamp", b"actionTimestamp", "actionType", b"actionType", "attachmentInterventionAction", b"attachmentInterventionAction", "chatAction", b"chatAction", "messageAction", b"messageAction", "spectraAction", b"spectraAction"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionTimestamp", b"actionTimestamp", "actionType", b"actionType", "attachmentInterventionAction", b"attachmentInterventionAction", "chatAction", b"chatAction", "messageAction", b"messageAction", "spectraAction", b"spectraAction"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_actionType: typing_extensions.TypeAlias = typing.Literal["chatAction", "messageAction", "spectraAction", "attachmentInterventionAction"]
            _WhichOneofArgType_actionType: typing_extensions.TypeAlias = typing.Literal["actionType", b"actionType"]
            def WhichOneof(self, oneof_group: _WhichOneofArgType_actionType) -> _WhichOneofReturnType_actionType | None: ...

        @typing.final
        class MetadataSyncNotification(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ACTIONS_FIELD_NUMBER: builtins.int
            @property
            def actions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Armadillo.ApplicationData.MetadataSyncAction]: ...
            def __init__(
                self,
                *,
                actions: collections.abc.Iterable[Global___Armadillo.ApplicationData.MetadataSyncAction] | None = ...,
            ) -> None: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actions", b"actions"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        METADATASYNC_FIELD_NUMBER: builtins.int
        AIBOTRESPONSE_FIELD_NUMBER: builtins.int
        MESSAGEHISTORYDOCUMENTMESSAGE_FIELD_NUMBER: builtins.int
        @property
        def metadataSync(self) -> Global___Armadillo.ApplicationData.MetadataSyncNotification: ...
        @property
        def aiBotResponse(self) -> Global___Armadillo.ApplicationData.AIBotResponseMessage: ...
        @property
        def messageHistoryDocumentMessage(self) -> Global___Armadillo.ApplicationData.MessageHistoryDocumentMessage: ...
        def __init__(
            self,
            *,
            metadataSync: Global___Armadillo.ApplicationData.MetadataSyncNotification | None = ...,
            aiBotResponse: Global___Armadillo.ApplicationData.AIBotResponseMessage | None = ...,
            messageHistoryDocumentMessage: Global___Armadillo.ApplicationData.MessageHistoryDocumentMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["aiBotResponse", b"aiBotResponse", "applicationData", b"applicationData", "messageHistoryDocumentMessage", b"messageHistoryDocumentMessage", "metadataSync", b"metadataSync"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["aiBotResponse", b"aiBotResponse", "applicationData", b"applicationData", "messageHistoryDocumentMessage", b"messageHistoryDocumentMessage", "metadataSync", b"metadataSync"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_applicationData: typing_extensions.TypeAlias = typing.Literal["metadataSync", "aiBotResponse", "messageHistoryDocumentMessage"]
        _WhichOneofArgType_applicationData: typing_extensions.TypeAlias = typing.Literal["applicationData", b"applicationData"]
        def WhichOneof(self, oneof_group: _WhichOneofArgType_applicationData) -> _WhichOneofReturnType_applicationData | None: ...

    @typing.final
    class Content(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class PaymentsTransactionMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _PaymentStatus:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _PaymentStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                PAYMENT_UNKNOWN: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 0
                REQUEST_INITED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 4
                REQUEST_DECLINED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 5
                REQUEST_TRANSFER_INITED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 6
                REQUEST_TRANSFER_COMPLETED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 7
                REQUEST_TRANSFER_FAILED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 8
                REQUEST_CANCELED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 9
                REQUEST_EXPIRED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 10
                TRANSFER_INITED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 11
                TRANSFER_PENDING: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 12
                TRANSFER_PENDING_RECIPIENT_VERIFICATION: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 13
                TRANSFER_CANCELED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 14
                TRANSFER_COMPLETED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 15
                TRANSFER_NO_RECEIVER_CREDENTIAL_NO_RTS_PENDING_CANCELED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 16
                TRANSFER_NO_RECEIVER_CREDENTIAL_NO_RTS_PENDING_OTHER: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 17
                TRANSFER_REFUNDED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 18
                TRANSFER_PARTIAL_REFUND: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 19
                TRANSFER_CHARGED_BACK: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 20
                TRANSFER_EXPIRED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 21
                TRANSFER_DECLINED: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 22
                TRANSFER_UNAVAILABLE: Armadillo.Content.PaymentsTransactionMessage._PaymentStatus.ValueType  # 23

            class PaymentStatus(_PaymentStatus, metaclass=_PaymentStatusEnumTypeWrapper): ...
            PAYMENT_UNKNOWN: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 0
            REQUEST_INITED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 4
            REQUEST_DECLINED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 5
            REQUEST_TRANSFER_INITED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 6
            REQUEST_TRANSFER_COMPLETED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 7
            REQUEST_TRANSFER_FAILED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 8
            REQUEST_CANCELED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 9
            REQUEST_EXPIRED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 10
            TRANSFER_INITED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 11
            TRANSFER_PENDING: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 12
            TRANSFER_PENDING_RECIPIENT_VERIFICATION: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 13
            TRANSFER_CANCELED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 14
            TRANSFER_COMPLETED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 15
            TRANSFER_NO_RECEIVER_CREDENTIAL_NO_RTS_PENDING_CANCELED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 16
            TRANSFER_NO_RECEIVER_CREDENTIAL_NO_RTS_PENDING_OTHER: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 17
            TRANSFER_REFUNDED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 18
            TRANSFER_PARTIAL_REFUND: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 19
            TRANSFER_CHARGED_BACK: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 20
            TRANSFER_EXPIRED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 21
            TRANSFER_DECLINED: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 22
            TRANSFER_UNAVAILABLE: Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType  # 23

            TRANSACTIONID_FIELD_NUMBER: builtins.int
            AMOUNT_FIELD_NUMBER: builtins.int
            CURRENCY_FIELD_NUMBER: builtins.int
            PAYMENTSTATUS_FIELD_NUMBER: builtins.int
            EXTENDEDCONTENTMESSAGE_FIELD_NUMBER: builtins.int
            transactionID: builtins.int
            amount: builtins.str
            currency: builtins.str
            paymentStatus: Global___Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType
            @property
            def extendedContentMessage(self) -> waArmadilloXMA.WAArmadilloXMA_pb2.ExtendedContentMessage: ...
            def __init__(
                self,
                *,
                transactionID: builtins.int | None = ...,
                amount: builtins.str | None = ...,
                currency: builtins.str | None = ...,
                paymentStatus: Global___Armadillo.Content.PaymentsTransactionMessage.PaymentStatus.ValueType | None = ...,
                extendedContentMessage: waArmadilloXMA.WAArmadilloXMA_pb2.ExtendedContentMessage | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["amount", b"amount", "currency", b"currency", "extendedContentMessage", b"extendedContentMessage", "paymentStatus", b"paymentStatus", "transactionID", b"transactionID"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["amount", b"amount", "currency", b"currency", "extendedContentMessage", b"extendedContentMessage", "paymentStatus", b"paymentStatus", "transactionID", b"transactionID"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class NetworkVerificationMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            CODETEXT_FIELD_NUMBER: builtins.int
            codeText: builtins.str
            def __init__(
                self,
                *,
                codeText: builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["codeText", b"codeText"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["codeText", b"codeText"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class NoteReplyMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TEXTCONTENT_FIELD_NUMBER: builtins.int
            STICKERCONTENT_FIELD_NUMBER: builtins.int
            VIDEOCONTENT_FIELD_NUMBER: builtins.int
            NOTEID_FIELD_NUMBER: builtins.int
            NOTETEXT_FIELD_NUMBER: builtins.int
            NOTETIMESTAMPMS_FIELD_NUMBER: builtins.int
            noteID: builtins.str
            noteTimestampMS: builtins.int
            @property
            def textContent(self) -> waCommon.WACommon_pb2.MessageText: ...
            @property
            def stickerContent(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            @property
            def videoContent(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            @property
            def noteText(self) -> waCommon.WACommon_pb2.MessageText: ...
            def __init__(
                self,
                *,
                textContent: waCommon.WACommon_pb2.MessageText | None = ...,
                stickerContent: waCommon.WACommon_pb2.SubProtocol | None = ...,
                videoContent: waCommon.WACommon_pb2.SubProtocol | None = ...,
                noteID: builtins.str | None = ...,
                noteText: waCommon.WACommon_pb2.MessageText | None = ...,
                noteTimestampMS: builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["noteID", b"noteID", "noteReplyContent", b"noteReplyContent", "noteText", b"noteText", "noteTimestampMS", b"noteTimestampMS", "stickerContent", b"stickerContent", "textContent", b"textContent", "videoContent", b"videoContent"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["noteID", b"noteID", "noteReplyContent", b"noteReplyContent", "noteText", b"noteText", "noteTimestampMS", b"noteTimestampMS", "stickerContent", b"stickerContent", "textContent", b"textContent", "videoContent", b"videoContent"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_noteReplyContent: typing_extensions.TypeAlias = typing.Literal["textContent", "stickerContent", "videoContent"]
            _WhichOneofArgType_noteReplyContent: typing_extensions.TypeAlias = typing.Literal["noteReplyContent", b"noteReplyContent"]
            def WhichOneof(self, oneof_group: _WhichOneofArgType_noteReplyContent) -> _WhichOneofReturnType_noteReplyContent | None: ...

        @typing.final
        class BumpExistingMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            @property
            def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
            def __init__(
                self,
                *,
                key: waCommon.WACommon_pb2.MessageKey | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class ImageGalleryMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            IMAGES_FIELD_NUMBER: builtins.int
            @property
            def images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[waCommon.WACommon_pb2.SubProtocol]: ...
            def __init__(
                self,
                *,
                images: collections.abc.Iterable[waCommon.WACommon_pb2.SubProtocol] | None = ...,
            ) -> None: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["images", b"images"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class ScreenshotAction(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _ScreenshotType:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _ScreenshotTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Content.ScreenshotAction._ScreenshotType.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                SCREENSHOT_IMAGE: Armadillo.Content.ScreenshotAction._ScreenshotType.ValueType  # 1
                SCREEN_RECORDING: Armadillo.Content.ScreenshotAction._ScreenshotType.ValueType  # 2

            class ScreenshotType(_ScreenshotType, metaclass=_ScreenshotTypeEnumTypeWrapper): ...
            SCREENSHOT_IMAGE: Armadillo.Content.ScreenshotAction.ScreenshotType.ValueType  # 1
            SCREEN_RECORDING: Armadillo.Content.ScreenshotAction.ScreenshotType.ValueType  # 2

            SCREENSHOTTYPE_FIELD_NUMBER: builtins.int
            screenshotType: Global___Armadillo.Content.ScreenshotAction.ScreenshotType.ValueType
            def __init__(
                self,
                *,
                screenshotType: Global___Armadillo.Content.ScreenshotAction.ScreenshotType.ValueType | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["screenshotType", b"screenshotType"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["screenshotType", b"screenshotType"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class ExtendedContentMessageWithSear(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            SEARID_FIELD_NUMBER: builtins.int
            PAYLOAD_FIELD_NUMBER: builtins.int
            NATIVEURL_FIELD_NUMBER: builtins.int
            SEARASSOCIATEDMESSAGE_FIELD_NUMBER: builtins.int
            SEARSENTWITHMESSAGEID_FIELD_NUMBER: builtins.int
            searID: builtins.str
            payload: builtins.bytes
            nativeURL: builtins.str
            searSentWithMessageID: builtins.str
            @property
            def searAssociatedMessage(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            def __init__(
                self,
                *,
                searID: builtins.str | None = ...,
                payload: builtins.bytes | None = ...,
                nativeURL: builtins.str | None = ...,
                searAssociatedMessage: waCommon.WACommon_pb2.SubProtocol | None = ...,
                searSentWithMessageID: builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["nativeURL", b"nativeURL", "payload", b"payload", "searAssociatedMessage", b"searAssociatedMessage", "searID", b"searID", "searSentWithMessageID", b"searSentWithMessageID"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["nativeURL", b"nativeURL", "payload", b"payload", "searAssociatedMessage", b"searAssociatedMessage", "searID", b"searID", "searSentWithMessageID", b"searSentWithMessageID"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class RavenActionNotifMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _ActionType:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _ActionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Content.RavenActionNotifMessage._ActionType.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                PLAYED: Armadillo.Content.RavenActionNotifMessage._ActionType.ValueType  # 0
                SCREENSHOT: Armadillo.Content.RavenActionNotifMessage._ActionType.ValueType  # 1
                FORCE_DISABLE: Armadillo.Content.RavenActionNotifMessage._ActionType.ValueType  # 2

            class ActionType(_ActionType, metaclass=_ActionTypeEnumTypeWrapper): ...
            PLAYED: Armadillo.Content.RavenActionNotifMessage.ActionType.ValueType  # 0
            SCREENSHOT: Armadillo.Content.RavenActionNotifMessage.ActionType.ValueType  # 1
            FORCE_DISABLE: Armadillo.Content.RavenActionNotifMessage.ActionType.ValueType  # 2

            KEY_FIELD_NUMBER: builtins.int
            ACTIONTIMESTAMP_FIELD_NUMBER: builtins.int
            ACTIONTYPE_FIELD_NUMBER: builtins.int
            actionTimestamp: builtins.int
            actionType: Global___Armadillo.Content.RavenActionNotifMessage.ActionType.ValueType
            @property
            def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
            def __init__(
                self,
                *,
                key: waCommon.WACommon_pb2.MessageKey | None = ...,
                actionTimestamp: builtins.int | None = ...,
                actionType: Global___Armadillo.Content.RavenActionNotifMessage.ActionType.ValueType | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionTimestamp", b"actionTimestamp", "actionType", b"actionType", "key", b"key"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionTimestamp", b"actionTimestamp", "actionType", b"actionType", "key", b"key"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @typing.final
        class RavenMessage(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _EphemeralType:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _EphemeralTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Content.RavenMessage._EphemeralType.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                VIEW_ONCE: Armadillo.Content.RavenMessage._EphemeralType.ValueType  # 0
                ALLOW_REPLAY: Armadillo.Content.RavenMessage._EphemeralType.ValueType  # 1
                KEEP_IN_CHAT: Armadillo.Content.RavenMessage._EphemeralType.ValueType  # 2

            class EphemeralType(_EphemeralType, metaclass=_EphemeralTypeEnumTypeWrapper): ...
            VIEW_ONCE: Armadillo.Content.RavenMessage.EphemeralType.ValueType  # 0
            ALLOW_REPLAY: Armadillo.Content.RavenMessage.EphemeralType.ValueType  # 1
            KEEP_IN_CHAT: Armadillo.Content.RavenMessage.EphemeralType.ValueType  # 2

            IMAGEMESSAGE_FIELD_NUMBER: builtins.int
            VIDEOMESSAGE_FIELD_NUMBER: builtins.int
            EPHEMERALTYPE_FIELD_NUMBER: builtins.int
            ephemeralType: Global___Armadillo.Content.RavenMessage.EphemeralType.ValueType
            @property
            def imageMessage(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            @property
            def videoMessage(self) -> waCommon.WACommon_pb2.SubProtocol: ...
            def __init__(
                self,
                *,
                imageMessage: waCommon.WACommon_pb2.SubProtocol | None = ...,
                videoMessage: waCommon.WACommon_pb2.SubProtocol | None = ...,
                ephemeralType: Global___Armadillo.Content.RavenMessage.EphemeralType.ValueType | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["ephemeralType", b"ephemeralType", "imageMessage", b"imageMessage", "mediaContent", b"mediaContent", "videoMessage", b"videoMessage"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ephemeralType", b"ephemeralType", "imageMessage", b"imageMessage", "mediaContent", b"mediaContent", "videoMessage", b"videoMessage"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_mediaContent: typing_extensions.TypeAlias = typing.Literal["imageMessage", "videoMessage"]
            _WhichOneofArgType_mediaContent: typing_extensions.TypeAlias = typing.Literal["mediaContent", b"mediaContent"]
            def WhichOneof(self, oneof_group: _WhichOneofArgType_mediaContent) -> _WhichOneofReturnType_mediaContent | None: ...

        @typing.final
        class CommonSticker(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _StickerType:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _StickerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Armadillo.Content.CommonSticker._StickerType.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                SMALL_LIKE: Armadillo.Content.CommonSticker._StickerType.ValueType  # 1
                MEDIUM_LIKE: Armadillo.Content.CommonSticker._StickerType.ValueType  # 2
                LARGE_LIKE: Armadillo.Content.CommonSticker._StickerType.ValueType  # 3

            class StickerType(_StickerType, metaclass=_StickerTypeEnumTypeWrapper): ...
            SMALL_LIKE: Armadillo.Content.CommonSticker.StickerType.ValueType  # 1
            MEDIUM_LIKE: Armadillo.Content.CommonSticker.StickerType.ValueType  # 2
            LARGE_LIKE: Armadillo.Content.CommonSticker.StickerType.ValueType  # 3

            STICKERTYPE_FIELD_NUMBER: builtins.int
            stickerType: Global___Armadillo.Content.CommonSticker.StickerType.ValueType
            def __init__(
                self,
                *,
                stickerType: Global___Armadillo.Content.CommonSticker.StickerType.ValueType | None = ...,
            ) -> None: ...
            _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["stickerType", b"stickerType"]
            def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
            _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["stickerType", b"stickerType"]
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        COMMONSTICKER_FIELD_NUMBER: builtins.int
        SCREENSHOTACTION_FIELD_NUMBER: builtins.int
        EXTENDEDCONTENTMESSAGE_FIELD_NUMBER: builtins.int
        RAVENMESSAGE_FIELD_NUMBER: builtins.int
        RAVENACTIONNOTIFMESSAGE_FIELD_NUMBER: builtins.int
        EXTENDEDMESSAGECONTENTWITHSEAR_FIELD_NUMBER: builtins.int
        IMAGEGALLERYMESSAGE_FIELD_NUMBER: builtins.int
        PAYMENTSTRANSACTIONMESSAGE_FIELD_NUMBER: builtins.int
        BUMPEXISTINGMESSAGE_FIELD_NUMBER: builtins.int
        NOTEREPLYMESSAGE_FIELD_NUMBER: builtins.int
        RAVENMESSAGEMSGR_FIELD_NUMBER: builtins.int
        NETWORKVERIFICATIONMESSAGE_FIELD_NUMBER: builtins.int
        @property
        def commonSticker(self) -> Global___Armadillo.Content.CommonSticker: ...
        @property
        def screenshotAction(self) -> Global___Armadillo.Content.ScreenshotAction: ...
        @property
        def extendedContentMessage(self) -> waArmadilloXMA.WAArmadilloXMA_pb2.ExtendedContentMessage: ...
        @property
        def ravenMessage(self) -> Global___Armadillo.Content.RavenMessage: ...
        @property
        def ravenActionNotifMessage(self) -> Global___Armadillo.Content.RavenActionNotifMessage: ...
        @property
        def extendedMessageContentWithSear(self) -> Global___Armadillo.Content.ExtendedContentMessageWithSear: ...
        @property
        def imageGalleryMessage(self) -> Global___Armadillo.Content.ImageGalleryMessage: ...
        @property
        def paymentsTransactionMessage(self) -> Global___Armadillo.Content.PaymentsTransactionMessage: ...
        @property
        def bumpExistingMessage(self) -> Global___Armadillo.Content.BumpExistingMessage: ...
        @property
        def noteReplyMessage(self) -> Global___Armadillo.Content.NoteReplyMessage: ...
        @property
        def ravenMessageMsgr(self) -> Global___Armadillo.Content.RavenMessage: ...
        @property
        def networkVerificationMessage(self) -> Global___Armadillo.Content.NetworkVerificationMessage: ...
        def __init__(
            self,
            *,
            commonSticker: Global___Armadillo.Content.CommonSticker | None = ...,
            screenshotAction: Global___Armadillo.Content.ScreenshotAction | None = ...,
            extendedContentMessage: waArmadilloXMA.WAArmadilloXMA_pb2.ExtendedContentMessage | None = ...,
            ravenMessage: Global___Armadillo.Content.RavenMessage | None = ...,
            ravenActionNotifMessage: Global___Armadillo.Content.RavenActionNotifMessage | None = ...,
            extendedMessageContentWithSear: Global___Armadillo.Content.ExtendedContentMessageWithSear | None = ...,
            imageGalleryMessage: Global___Armadillo.Content.ImageGalleryMessage | None = ...,
            paymentsTransactionMessage: Global___Armadillo.Content.PaymentsTransactionMessage | None = ...,
            bumpExistingMessage: Global___Armadillo.Content.BumpExistingMessage | None = ...,
            noteReplyMessage: Global___Armadillo.Content.NoteReplyMessage | None = ...,
            ravenMessageMsgr: Global___Armadillo.Content.RavenMessage | None = ...,
            networkVerificationMessage: Global___Armadillo.Content.NetworkVerificationMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["bumpExistingMessage", b"bumpExistingMessage", "commonSticker", b"commonSticker", "content", b"content", "extendedContentMessage", b"extendedContentMessage", "extendedMessageContentWithSear", b"extendedMessageContentWithSear", "imageGalleryMessage", b"imageGalleryMessage", "networkVerificationMessage", b"networkVerificationMessage", "noteReplyMessage", b"noteReplyMessage", "paymentsTransactionMessage", b"paymentsTransactionMessage", "ravenActionNotifMessage", b"ravenActionNotifMessage", "ravenMessage", b"ravenMessage", "ravenMessageMsgr", b"ravenMessageMsgr", "screenshotAction", b"screenshotAction"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bumpExistingMessage", b"bumpExistingMessage", "commonSticker", b"commonSticker", "content", b"content", "extendedContentMessage", b"extendedContentMessage", "extendedMessageContentWithSear", b"extendedMessageContentWithSear", "imageGalleryMessage", b"imageGalleryMessage", "networkVerificationMessage", b"networkVerificationMessage", "noteReplyMessage", b"noteReplyMessage", "paymentsTransactionMessage", b"paymentsTransactionMessage", "ravenActionNotifMessage", b"ravenActionNotifMessage", "ravenMessage", b"ravenMessage", "ravenMessageMsgr", b"ravenMessageMsgr", "screenshotAction", b"screenshotAction"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_content: typing_extensions.TypeAlias = typing.Literal["commonSticker", "screenshotAction", "extendedContentMessage", "ravenMessage", "ravenActionNotifMessage", "extendedMessageContentWithSear", "imageGalleryMessage", "paymentsTransactionMessage", "bumpExistingMessage", "noteReplyMessage", "ravenMessageMsgr", "networkVerificationMessage"]
        _WhichOneofArgType_content: typing_extensions.TypeAlias = typing.Literal["content", b"content"]
        def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

    PAYLOAD_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def payload(self) -> Global___Armadillo.Payload: ...
    @property
    def metadata(self) -> Global___Armadillo.Metadata: ...
    def __init__(
        self,
        *,
        payload: Global___Armadillo.Payload | None = ...,
        metadata: Global___Armadillo.Metadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["metadata", b"metadata", "payload", b"payload"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["metadata", b"metadata", "payload", b"payload"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Armadillo: typing_extensions.TypeAlias = Armadillo
