"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LIDMigrationMapping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PN_FIELD_NUMBER: builtins.int
    ASSIGNEDLID_FIELD_NUMBER: builtins.int
    LATESTLID_FIELD_NUMBER: builtins.int
    pn: builtins.int
    assignedLid: builtins.int
    latestLid: builtins.int
    def __init__(
        self,
        *,
        pn: builtins.int | None = ...,
        assignedLid: builtins.int | None = ...,
        latestLid: builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["assignedLid", b"assignedLid", "latestLid", b"latestLid", "pn", b"pn"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["assignedLid", b"assignedLid", "latestLid", b"latestLid", "pn", b"pn"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LIDMigrationMapping: typing_extensions.TypeAlias = LIDMigrationMapping

@typing.final
class LIDMigrationMappingSyncPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PNTOLIDMAPPINGS_FIELD_NUMBER: builtins.int
    CHATDBMIGRATIONTIMESTAMP_FIELD_NUMBER: builtins.int
    chatDbMigrationTimestamp: builtins.int
    @property
    def pnToLidMappings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LIDMigrationMapping]: ...
    def __init__(
        self,
        *,
        pnToLidMappings: collections.abc.Iterable[Global___LIDMigrationMapping] | None = ...,
        chatDbMigrationTimestamp: builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["chatDbMigrationTimestamp", b"chatDbMigrationTimestamp"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["chatDbMigrationTimestamp", b"chatDbMigrationTimestamp", "pnToLidMappings", b"pnToLidMappings"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LIDMigrationMappingSyncPayload: typing_extensions.TypeAlias = LIDMigrationMappingSyncPayload
