"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ActionLog(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTIONLOGREACTION_FIELD_NUMBER: builtins.int
    @property
    def actionLogReaction(self) -> Global___ActionLogReaction: ...
    def __init__(
        self,
        *,
        actionLogReaction: Global___ActionLogReaction | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionLogReaction", b"actionLogReaction", "actionLogSubtype", b"actionLogSubtype"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actionLogReaction", b"actionLogReaction", "actionLogSubtype", b"actionLogSubtype"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_actionLogSubtype: typing_extensions.TypeAlias = typing.Literal["actionLogReaction"]
    _WhichOneofArgType_actionLogSubtype: typing_extensions.TypeAlias = typing.Literal["actionLogSubtype", b"actionLogSubtype"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_actionLogSubtype) -> _WhichOneofReturnType_actionLogSubtype | None: ...

Global___ActionLog: typing_extensions.TypeAlias = ActionLog

@typing.final
class ActionLogReaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMOJIUNICODE_FIELD_NUMBER: builtins.int
    emojiUnicode: builtins.str
    def __init__(
        self,
        *,
        emojiUnicode: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["emojiUnicode", b"emojiUnicode"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["emojiUnicode", b"emojiUnicode"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionLogReaction: typing_extensions.TypeAlias = ActionLogReaction
