"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ExtendedTextMessage(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEXT_FIELD_NUMBER: builtins.int
        CONTEXTINFO_FIELD_NUMBER: builtins.int
        text: builtins.str
        @property
        def contextInfo(self) -> Global___Message.ContextInfo: ...
        def __init__(
            self,
            *,
            text: builtins.str | None = ...,
            contextInfo: Global___Message.ContextInfo | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["contextInfo", b"contextInfo", "text", b"text"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["contextInfo", b"contextInfo", "text", b"text"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class ContextInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STANZAID_FIELD_NUMBER: builtins.int
        PARTICIPANT_FIELD_NUMBER: builtins.int
        QUOTEDMESSAGE_FIELD_NUMBER: builtins.int
        stanzaID: builtins.str
        participant: builtins.str
        @property
        def quotedMessage(self) -> Global___Message: ...
        def __init__(
            self,
            *,
            stanzaID: builtins.str | None = ...,
            participant: builtins.str | None = ...,
            quotedMessage: Global___Message | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["participant", b"participant", "quotedMessage", b"quotedMessage", "stanzaID", b"stanzaID"]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["participant", b"participant", "quotedMessage", b"quotedMessage", "stanzaID", b"stanzaID"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CONVERSATION_FIELD_NUMBER: builtins.int
    EXTENDEDTEXTMESSAGE_FIELD_NUMBER: builtins.int
    MESSAGECONTEXTINFO_FIELD_NUMBER: builtins.int
    conversation: builtins.str
    @property
    def extendedTextMessage(self) -> Global___Message.ExtendedTextMessage: ...
    @property
    def messageContextInfo(self) -> Global___MessageContextInfo: ...
    def __init__(
        self,
        *,
        conversation: builtins.str | None = ...,
        extendedTextMessage: Global___Message.ExtendedTextMessage | None = ...,
        messageContextInfo: Global___MessageContextInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["conversation", b"conversation", "extendedTextMessage", b"extendedTextMessage", "messageContextInfo", b"messageContextInfo"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["conversation", b"conversation", "extendedTextMessage", b"extendedTextMessage", "messageContextInfo", b"messageContextInfo"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Message: typing_extensions.TypeAlias = Message

@typing.final
class MessageContextInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGESECRET_FIELD_NUMBER: builtins.int
    messageSecret: builtins.bytes
    def __init__(
        self,
        *,
        messageSecret: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageSecret", b"messageSecret"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["messageSecret", b"messageSecret"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MessageContextInfo: typing_extensions.TypeAlias = MessageContextInfo
