"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
import waSyncAction.WAWebProtobufSyncAction_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SyncdSnapshotRecovery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    COLLECTIONNAME_FIELD_NUMBER: builtins.int
    MUTATIONRECORDS_FIELD_NUMBER: builtins.int
    COLLECTIONLTHASH_FIELD_NUMBER: builtins.int
    collectionName: builtins.str
    collectionLthash: builtins.bytes
    @property
    def version(self) -> Global___SyncdVersion: ...
    @property
    def mutationRecords(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SyncdPlainTextRecord]: ...
    def __init__(
        self,
        *,
        version: Global___SyncdVersion | None = ...,
        collectionName: builtins.str | None = ...,
        mutationRecords: collections.abc.Iterable[Global___SyncdPlainTextRecord] | None = ...,
        collectionLthash: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["collectionLthash", b"collectionLthash", "collectionName", b"collectionName", "version", b"version"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["collectionLthash", b"collectionLthash", "collectionName", b"collectionName", "mutationRecords", b"mutationRecords", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdSnapshotRecovery: typing_extensions.TypeAlias = SyncdSnapshotRecovery

@typing.final
class SyncdPlainTextRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    KEYID_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    keyID: builtins.bytes
    mac: builtins.bytes
    @property
    def value(self) -> waSyncAction.WAWebProtobufSyncAction_pb2.SyncActionData: ...
    def __init__(
        self,
        *,
        value: waSyncAction.WAWebProtobufSyncAction_pb2.SyncActionData | None = ...,
        keyID: builtins.bytes | None = ...,
        mac: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["keyID", b"keyID", "mac", b"mac", "value", b"value"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["keyID", b"keyID", "mac", b"mac", "value", b"value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdPlainTextRecord: typing_extensions.TypeAlias = SyncdPlainTextRecord

@typing.final
class SyncdVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.int
    def __init__(
        self,
        *,
        version: builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["version", b"version"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdVersion: typing_extensions.TypeAlias = SyncdVersion
