"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SyncdMutation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SyncdOperation:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SyncdOperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SyncdMutation._SyncdOperation.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SET: SyncdMutation._SyncdOperation.ValueType  # 0
        REMOVE: SyncdMutation._SyncdOperation.ValueType  # 1

    class SyncdOperation(_SyncdOperation, metaclass=_SyncdOperationEnumTypeWrapper): ...
    SET: SyncdMutation.SyncdOperation.ValueType  # 0
    REMOVE: SyncdMutation.SyncdOperation.ValueType  # 1

    OPERATION_FIELD_NUMBER: builtins.int
    RECORD_FIELD_NUMBER: builtins.int
    operation: Global___SyncdMutation.SyncdOperation.ValueType
    @property
    def record(self) -> Global___SyncdRecord: ...
    def __init__(
        self,
        *,
        operation: Global___SyncdMutation.SyncdOperation.ValueType | None = ...,
        record: Global___SyncdRecord | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["operation", b"operation", "record", b"record"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["operation", b"operation", "record", b"record"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdMutation: typing_extensions.TypeAlias = SyncdMutation

@typing.final
class SyncdVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.int
    def __init__(
        self,
        *,
        version: builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["version", b"version"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdVersion: typing_extensions.TypeAlias = SyncdVersion

@typing.final
class ExitCode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    code: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        code: builtins.int | None = ...,
        text: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["code", b"code", "text", b"text"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["code", b"code", "text", b"text"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExitCode: typing_extensions.TypeAlias = ExitCode

@typing.final
class SyncdIndex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOB_FIELD_NUMBER: builtins.int
    blob: builtins.bytes
    def __init__(
        self,
        *,
        blob: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blob", b"blob"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blob", b"blob"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdIndex: typing_extensions.TypeAlias = SyncdIndex

@typing.final
class SyncdValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOB_FIELD_NUMBER: builtins.int
    blob: builtins.bytes
    def __init__(
        self,
        *,
        blob: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["blob", b"blob"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["blob", b"blob"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdValue: typing_extensions.TypeAlias = SyncdValue

@typing.final
class KeyId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ID: builtins.bytes
    def __init__(
        self,
        *,
        ID: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["ID", b"ID"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ID", b"ID"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KeyId: typing_extensions.TypeAlias = KeyId

@typing.final
class SyncdRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    KEYID_FIELD_NUMBER: builtins.int
    @property
    def index(self) -> Global___SyncdIndex: ...
    @property
    def value(self) -> Global___SyncdValue: ...
    @property
    def keyID(self) -> Global___KeyId: ...
    def __init__(
        self,
        *,
        index: Global___SyncdIndex | None = ...,
        value: Global___SyncdValue | None = ...,
        keyID: Global___KeyId | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["index", b"index", "keyID", b"keyID", "value", b"value"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["index", b"index", "keyID", b"keyID", "value", b"value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdRecord: typing_extensions.TypeAlias = SyncdRecord

@typing.final
class ExternalBlobReference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEDIAKEY_FIELD_NUMBER: builtins.int
    DIRECTPATH_FIELD_NUMBER: builtins.int
    HANDLE_FIELD_NUMBER: builtins.int
    FILESIZEBYTES_FIELD_NUMBER: builtins.int
    FILESHA256_FIELD_NUMBER: builtins.int
    FILEENCSHA256_FIELD_NUMBER: builtins.int
    mediaKey: builtins.bytes
    directPath: builtins.str
    handle: builtins.str
    fileSizeBytes: builtins.int
    fileSHA256: builtins.bytes
    fileEncSHA256: builtins.bytes
    def __init__(
        self,
        *,
        mediaKey: builtins.bytes | None = ...,
        directPath: builtins.str | None = ...,
        handle: builtins.str | None = ...,
        fileSizeBytes: builtins.int | None = ...,
        fileSHA256: builtins.bytes | None = ...,
        fileEncSHA256: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["directPath", b"directPath", "fileEncSHA256", b"fileEncSHA256", "fileSHA256", b"fileSHA256", "fileSizeBytes", b"fileSizeBytes", "handle", b"handle", "mediaKey", b"mediaKey"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["directPath", b"directPath", "fileEncSHA256", b"fileEncSHA256", "fileSHA256", b"fileSHA256", "fileSizeBytes", b"fileSizeBytes", "handle", b"handle", "mediaKey", b"mediaKey"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExternalBlobReference: typing_extensions.TypeAlias = ExternalBlobReference

@typing.final
class SyncdSnapshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    KEYID_FIELD_NUMBER: builtins.int
    mac: builtins.bytes
    @property
    def version(self) -> Global___SyncdVersion: ...
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SyncdRecord]: ...
    @property
    def keyID(self) -> Global___KeyId: ...
    def __init__(
        self,
        *,
        version: Global___SyncdVersion | None = ...,
        records: collections.abc.Iterable[Global___SyncdRecord] | None = ...,
        mac: builtins.bytes | None = ...,
        keyID: Global___KeyId | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["keyID", b"keyID", "mac", b"mac", "version", b"version"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["keyID", b"keyID", "mac", b"mac", "records", b"records", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdSnapshot: typing_extensions.TypeAlias = SyncdSnapshot

@typing.final
class SyncdMutations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MUTATIONS_FIELD_NUMBER: builtins.int
    @property
    def mutations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SyncdMutation]: ...
    def __init__(
        self,
        *,
        mutations: collections.abc.Iterable[Global___SyncdMutation] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["mutations", b"mutations"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdMutations: typing_extensions.TypeAlias = SyncdMutations

@typing.final
class SyncdPatch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    MUTATIONS_FIELD_NUMBER: builtins.int
    EXTERNALMUTATIONS_FIELD_NUMBER: builtins.int
    SNAPSHOTMAC_FIELD_NUMBER: builtins.int
    PATCHMAC_FIELD_NUMBER: builtins.int
    KEYID_FIELD_NUMBER: builtins.int
    EXITCODE_FIELD_NUMBER: builtins.int
    DEVICEINDEX_FIELD_NUMBER: builtins.int
    CLIENTDEBUGDATA_FIELD_NUMBER: builtins.int
    snapshotMAC: builtins.bytes
    patchMAC: builtins.bytes
    deviceIndex: builtins.int
    clientDebugData: builtins.bytes
    @property
    def version(self) -> Global___SyncdVersion: ...
    @property
    def mutations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SyncdMutation]: ...
    @property
    def externalMutations(self) -> Global___ExternalBlobReference: ...
    @property
    def keyID(self) -> Global___KeyId: ...
    @property
    def exitCode(self) -> Global___ExitCode: ...
    def __init__(
        self,
        *,
        version: Global___SyncdVersion | None = ...,
        mutations: collections.abc.Iterable[Global___SyncdMutation] | None = ...,
        externalMutations: Global___ExternalBlobReference | None = ...,
        snapshotMAC: builtins.bytes | None = ...,
        patchMAC: builtins.bytes | None = ...,
        keyID: Global___KeyId | None = ...,
        exitCode: Global___ExitCode | None = ...,
        deviceIndex: builtins.int | None = ...,
        clientDebugData: builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["clientDebugData", b"clientDebugData", "deviceIndex", b"deviceIndex", "exitCode", b"exitCode", "externalMutations", b"externalMutations", "keyID", b"keyID", "patchMAC", b"patchMAC", "snapshotMAC", b"snapshotMAC", "version", b"version"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["clientDebugData", b"clientDebugData", "deviceIndex", b"deviceIndex", "exitCode", b"exitCode", "externalMutations", b"externalMutations", "keyID", b"keyID", "mutations", b"mutations", "patchMAC", b"patchMAC", "snapshotMAC", b"snapshotMAC", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SyncdPatch: typing_extensions.TypeAlias = SyncdPatch
